language: go

go:
 - 1.8.3
 - tip

matrix:
  fast_finish: true

sudo: false

env:
  global:
   - GOBIN=$HOME/bin
   - PATH=$HOME/bin:$PATH

install:
 - go get -t -v -u ./...

script:
 - go tool vet -all .
 - go build ./...
 - go test -race -v ./...
